# Generated by Django 4.1.7 on 2023-02-26 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, unique=True)),
                ('group_image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.groupmodel', to_field='group_name')),
            ],
        ),
        migrations.CreateModel(
            name='LoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=70, null=True)),
                ('item_description', models.TextField()),
                ('item_type', models.ManyToManyField(to='base.lore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
